### ISSUE TITLE
Modificar OptionPerVote en BD

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#13]
Desde recuento de votos necesitamos implementar un nuevo campo integer dentro de la clase OptionPerVote.

El nuevo campo permite hacer un recuento teniendo en cuenta el orden de las posibles respuestas, podría ser 0 no null,  el valor vendría dado por la preferencia que de el votante a cada respuesta.

Desde integración nos han solicitado vuestra confirmación.

**Comment by elvgarrui** [comment]
Ese cambio supondría más cambios en la BBDD: Un boolean en la clase Respuesta que sea True si es una pregunta con prioridad y False si no. ¿Merece realmente la pena hacer este tipo de cambios en la BBDD a estas alturas en el proyecto? @DominMuda @ArturoRonda

**Comment by ArturoRonda** [comment]
El cambio seria en la clase optionPerVote y nos permitirá realizar recuentos teniendo en cuenta la prioridad de cada respuesta a la hora de hacer el recuento.

**Comment by elvgarrui** [comment]
Pero la clase OptionPerVote a nosotros no nos afecta directamente. Lo que si nos afecta es que queráis que las Question sean preguntas con o sin prioridad. ¿O todas las preguntas tienen prioridad?

De todas formas nosotros controlamos desde Poll hasta Question_Option; OptionPerVote es la unión de votaciones con opciones, y es parte de cabina de votaciones.
