### ISSUE TITLE
Planificación Milestone 2

### ISSUE THREAD

**Issue by elvgarrui** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#3]
Planificación de trabajo del milestone teniendo en cuenta los cambios que se han realizado en el proyecto tras la reunión de coordinación.

**Comment by DominMuda** [comment]
- Toda acción que afecte a la DB vendrá precedida por una comprobación de la identidad del usuario a través de Login.
- Es necesario poder redireccionar a un formulario de creación de censos gestionado por Administración de Censos.
- En nuestro formulario de creación de votaciones dispondremos de un desplegable en el que seleccionar el censo al que irá enfocado la votación.
- Las votaciones podrán ser opcionales y de respuesta múltiple.
