### ISSUE TITLE
Creación del contenedor Docker

### ISSUE THREAD

**Issue by elvgarrui** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#31]
A petición de Integración, debemos tener un contenedor Docker con la aplicación y el incremento funcional.

**Comment by elvgarrui** [comment]
Tenemos un problema con el fichero tomcat-users.xml
Aquí hay una solución propuesta por un usuario de StackOverflow para el problema:
https://stackoverflow.com/questions/46052973/how-to-deploy-war-file-in-tomcat-7-of-docker-container

**Comment by YamiJosema** [comment]
Comenzamos a generar nuestro Dockerfile haciendo uso de esta guía:
https://runnable.com/docker/java/dockerize-your-java-application

**Comment by elvgarrui** [comment]
Se ha creado con éxito el contenedor con un servidor Tomcat en el puerto especificado (52001)
Esta versión no se integra con Maven y usa root como usuario.
