### ISSUE TITLE
Cambio de usuario de la BBDD

### ISSUE THREAD

**Issue by elvgarrui** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#39]
Ahora mismo usamos la BBDD en local, pero en el server de integración usaremos el usuario que nos corresponda, para poder subir el contenedor Docker a DockerHub.

**Comment by YamiJosema** [comment]
Cierre para nuevo comienzo del proyecto haciendo uso de Python 2.7 con Django 1.5
