### ISSUE TITLE
Diseño de mockups

### ISSUE THREAD

**Issue by DominMuda** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#4]
Será necesario realizar mockups de:

- Master Page (con footer y header)
- Creación de votaciones 
   - Vista de llegada al formulario
   - Vista con todas las opciones desplegadas
- Posible visualización de la votación antes de su envío

(La herramiento de diseño de mockup puede ser de elección libre)

**Comment by YamiJosema** [comment]
Cierre para nuevo comienzo
