### ISSUE TITLE
Automatización de la construcción

### ISSUE THREAD

**Issue by elvgarrui** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#40]
Se debe conseguir que con ayuda de TravisCI se genere automáticamente un ejecutable cada vez que se termina una funcionalidad y se sube a Master.

**Comment by DominMuda** [comment]
La actualización del docker en DockerHub a través de Travis-ci.com se puede realizar siguiendo el siguiente tutorial https://docs.travis-ci.com/user/docker/

**Comment by YamiJosema** [comment]
Cierre para nuevo comienzo del proyecto haciendo uso de Python 2.7 con Django 1.5
