### ISSUE TITLE
Errores Creación de Votaciones

### ISSUE THREAD

**Issue by YamiJosema** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#45]
Al intentar crear una "poll", aparecen errores en el atributo "census", "endDate" y "startDate".

**Comment by anapareciendo** [comment]
Surge un nuevo problema con la generación automatica de las primary keys desde hibernate.

Código de error: Table 'votaciones_splc.hibernate_sequences' doesn't exist.

**Comment by YamiJosema** [comment]
Desplegamos el proyecto en local haciendo uso de Tomcat en Eclipse, accedemos a la pestaña de "Nueva Encuesta", introducimos los datos y guardamos.
Esto genera un error de hibernate debido a las dependencias que tiene el proyecto heredado.
Se probó con un proyecto de ejemplo de Maven siguiendo el siguiente [tutorial](http://www.codejava.net/frameworks/spring/creating-a-spring-mvc-project-using-maven-and-eclipse-in-one-minute), pero se encontraros problemas de compatibilidad a la hora de crear el proyecto de ejemplo.
Debido a los problemas ocasionados por el código heredado, se ha tomado la decisión de comenzar de nuevo, ignorando el código heredado y haciendo uso de tecnologías diferentes para conseguir llegar a nuestros objetivos.
