### ISSUE TITLE
Implementación del dominio

### ISSUE THREAD

**Issue by DominMuda** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#5]
Implementar el modelo de dominio, servicios y repositorio en Java basándose en el modelo relacional dado por el grupo de integración en:

[Modelo_Relacional_Sistema_Votaciones.pdf](https://github.com/Proyecto-EGC-G1/AdminVotaciones-EGC-G1/files/1513162/Modelo_Relacional_Sistema_Votaciones.pdf)

**Comment by YamiJosema** [comment]
Cierre para nuevo comienzo del proyecto haciendo uso de Python 2.7 con Django 1.5
