### ISSUE TITLE
Tarea: Conexión con MariaDB

### ISSUE THREAD

**Issue by DominMuda** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#52]
Establecer en "settings.py" la siguiente configuración

1. Se usará MySQL
2. Configurar base de datos "votaciones_splc" usando user y pass distribuido por Integración

Se creará un script de conexión con base de datos llamado "dbConnect" dentro del paquete "admvotes" con el que se accederá a la base de datos desde las vistas y los tests.
  
 Además, se creará una lista html que muestre todas las votaciones, para asegurar que la conexión se ha realizado correctamente.

**Comment by anapareciendo** [comment]
Error al ejecutar el proyecto:
"TypeError: init() got an unexpected keyword argument 'balnk'"
Este error ocurre en la clase Question, en el atributo title. La opción "blank" estaba mal escrita.

**Comment by elvgarrui** [comment]
Para conseguir una conexión con éxito desde Windows se han seguido los siguientes pasos:

1. Instalación de MySQL
2. Instalación del conector de python2.7 con Mysql.
3. Instalación de Microsoft Visual C++ Compiler for Python 2.7 https://www.microsoft.com/en-us/download/details.aspx?id=44266
4. Instalación con pip de python-mysql
5. Creación de docker con MariaDB en el puerto 3306

**Comment by DominMuda** [comment]
Para la conexión desde Mac/Linux (Debian) habrá que instalar los siguientes paquetes
1. mysql-server
2. libmysqlclient-dev
3. python-dev
4. MySQL-Python 1.2.5 https://pypi.python.org/pypi/MySQL-python/1.2.5

Posteriormente crear el docker con MariaDB en el puerto 3306

**Comment by DominMuda** [comment]
Para el uso de scripts en base de datos se usará MySQLWorkbench:
- Windows/Mac/Ubuntu https://dev.mysql.com/downloads/workbench/
- LinuxMint https://community.linuxmint.com/software/view/mysql-workbench

**Comment by anapareciendo** [comment]
Para la conexión desde Mac ha sido necesario instalar mysql-server y ejecutar los siguientes comandos en consola:

1. export PATH=$PATH:/usr/local/mysql/bin
2. sudo easy_install mysql-python

**Comment by YamiJosema** [comment]
Al hacer _pip install mysql-python_ se obtiene el siguiente error:
```
_mysql.c(42) : fatal error C1083: Cannot open include file: 'config-win.h': No such file or directory
    error: command 'C:\\Users\\Josema\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2
```

Para poder instalar mysql con python y evitar así dicho error, tendremos que usar _Wheel_. 
1. Si no tenemos isntalado _Wheel_: _pip install wheel_
2. Descargaremos la version de mysql-python que necesitemos del siguiente [enlace](https://www.lfd.uci.edu/~gohlke/pythonlibs/#mysql-python)
3. Nos iremos al direcctorio en el que hemos descargado el archivo .whl
4. _pip install MySQL_python-1.2.5-cp27-none-win32.whl_ (el nombre del archivo podrá variar según la versión de python que tengamos instalada)
