### ISSUE TITLE
Tarea: Integración con TravisCI

### ISSUE THREAD

**Issue by JavierCenteno** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#53]
Realizar la integración con [TravisCI](https://docs.travis-ci.com/) del proyecto. Para ello, es necesario configurar TravisCI especificando en el archivo de configuración:
1. Lenguaje y versión del lenguaje usados
2. Fichero* que contiene las herramientas que necesitan ser instaladas
3. Pruebas que deben ser ejecutadas
4. Servicios que necesitan ser iniciados
5. Conexión a la base de datos
6. Creación y población de la base de datos

*Será necesaria la creación de un fichero que contenga todas las herramientas y sus respectivas versiones.
  
 Rama asociada: test

**Comment by elvgarrui** [comment]
@anapareciendo 
Es posible contruir directamente nuestro proyecto en un docker usando TravisCI

Recursos útiles:
- Documentación oficial: https://docs.travis-ci.com/user/docker/
- Ejemplo: https://gist.github.com/BretFisher/14cd228f0d7e40dae085

**Comment by elvgarrui** [comment]
En este gist proponen una solución interesante para la conexión de BBDD usando la variable de entorno de Travis: https://gist.github.com/ndarville/3625246

**Comment by elvgarrui** [comment]
He creado un repositorio aparte (https://github.com/elvgarrui/admvts) con nuestro código donde poder probar Travis mientras ocurrían problemas de supuesto "abuso" de la plataforma por parte de nuestra organización.

En dicho repositorio se ha terminado de configurar con éxito el `.travis.yml `del proyecto.

**Comment by elvgarrui** [comment]
De los `tests.py`, ahora funciona el test básico 1+1=2, pero falla el de creación de objetos en la BBDD

**Comment by elvgarrui** [comment]
Todas las builds se realizan sin error en las ramas.
