### ISSUE TITLE
Implementación de controladores y conversores

### ISSUE THREAD

**Issue by DominMuda** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#6]
Basándose en la definición del dominio de Java y las necesidades de las vistas a desplegar según sea especificado en mockups, se deberá implementar los controladores y conversores necesarios para el diseño de las vistas.

**Comment by YamiJosema** [comment]
Cierre para nuevo comienzo del proyecto haciendo uso de Python 2.7 con Django 1.5
