### ISSUE TITLE
Tarea: Listar votaciones disponibles para usuario conectado

### ISSUE THREAD

**Issue by DominMuda** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#63]
Se realizará una modificación de la lista de votaciones para que solo aparezcan las votaciones en las que el usuario conectado puede participar según los censos a los que pertenezca. Para ello será necesario añadir al modelo de datos:

1. _userAccountPerCensus_, que relaciona los objetos del modelo _userAccount_ y _census_ definidos en #61

**Comment by DominMuda** [comment]
Será necesario implementar también implementar la clase _userAccount_

**Comment by YamiJosema** [comment]
Las votaciones en las que la comunidad autónoma sea igual a la comunidad autónoma del usuario logado, también se considerará votaciones en las que el usuario pueda votar.
Será necesario añadir las votaciones, en las que coincida la comunidad autónoma, a la lista de votaciones disponibles que aparece en la página principal.
