### ISSUE TITLE
Tarea: Cabecera funcional

### ISSUE THREAD

**Issue by elvgarrui** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#65]
Se añadirán las URLs de los distintos módulos al `header.html` para que se pueda navegar entre los distintos apartados del sistema de votaciones.

Las URLs a añadir son:

- Autenticación: https://g1login.egc.duckdns.org/login
- Cabina de votaciones:  g1cabinaweb.egc.duckdns.org/cabin/{numCabina}

Para poder mostrar un ejemplo funcional de cabina, se pondrá una URL de ejemplo (numCabina = 1)
Por último, a petición de Integración, se cambiará base.html para que el titulo de la web sea "ADM Votaciones" en vez de "EGC"

**Comment by YamiJosema** [comment]
El menú principal diseñado por el grupo de integración, consta de diversas pestañas que enlazan a los distintos subsistemas.  Teniendo en cuenta la implementación del subsistema de Cabina de Votaciones, la pestaña dedicada a ellos en el menú principal no tiene ninguna utilidad. 

`https://g1cabinaweb.egc.duckdns.org/cabin/{{poll.id}}/`
En la lista de votaciones, se añadirá un link con ese formato, donde _id_ será el identificador de la votación. Al acceder, se llegara a una página donde ya se permitirá votar.

La pestaña del menú principal para cabina de votaciones pasará a estar deshabilitada, no conteniendo ningún enlace.

**Comment by YamiJosema** [comment]
Vamos a prescindir de la pestaña del menú principal que llevaba a cabina de votaciones, la cual no tenia ningún uso. Esta decisión ha sido tomada por el grupo de integración.
La pestaña de login será sustituida por una pestaña de logout, teniendo esta mucho mas uso y sentido, ya que el login se hace de forma aislada. La nueva pestaña enlazara al servicio de logout ofrecido por el grupo de integración. Esta decisión ha sido tomada por el grupo de integración.

**Comment by YamiJosema** [comment]
No todas las pestañas del menú principal tienen uso, debido a que no todos los subsistemas están terminados y subidos al servidor. 
Si fuera necesario, la tarea se reabriría para incluir los enlaces de los faltantes.
