### ISSUE TITLE
Definición del formato de salida y envío en API

### ISSUE THREAD

**Issue by DominMuda** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#7]
Definición del formato y estructura del JSON a enviar a través de la API definida en la URI dada en 

https://github.com/Proyecto-EGC-G1/Integracion-EGC-G1/blob/master/Documentaci%C3%B3n/URIs%20y%20funcionalidades%20de%20cada%20subgrupo.pdf

Será necesario investigar y documentar el uso de swagger para la implementación del uso de la API

**Comment by YamiJosema** [comment]
Cierre para nuevo comienzo del proyecto haciendo uso de Python 2.7 con Django 1.5
