### ISSUE TITLE
Errores: Enlaces

### ISSUE THREAD

**Issue by anapareciendo** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#70]
Han surgido los siguientes errores en algunos de los enlaces de la aplicación:

1. En el header de la aplicación, hay que eliminar la pestaña de login, dejando solo la de logout.
2. En el fichero "url.py", en el último enlace, hay que poner un "detalles/" delante de lo que ya hay para aclarar dicho enlace y que la redirección sea correcta.

**Comment by YamiJosema** [comment]
El enlace a los detalles de la vista _lista.html_, debe actualizarse al nuevo patron de la url: `detalles/{{id}}`
