### ISSUE TITLE
Tarea: Lista de todas las votaciones

### ISSUE THREAD

**Issue by DominMuda** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#72]
Se propone crear una lista de todas las votaciones registradas en la base de datos, la cual esté disponible para cualquier usuario, independientemente de su rol. La versión actual del sistema, sólo permite ver las votaciones abiertas en las que el usuario logado puede votar, y las votaciones futuras a los usuarios con el rol de administrador, para que puedan editarlas. Que un usuario pueda ver todas las votaciones que hay en el sistema, tanto pasadas como futuras, puede traducirse en un mayor interés del usuario por nuestra aplicación. Conocer cuáles serán las votaciones futuras en las que podrá votar conseguirá que los usuarios puedan estar más atentos y hagan mayor uso de nuestra aplicación.

**Comment by anapareciendo** [comment]
Se han añadidio los test en el fichero test.py para el método busca_votaciones.
