### ISSUE TITLE
Implementación de vistas

### ISSUE THREAD

**Issue by DominMuda** [Proyecto-EGC-G1/AdminVotaciones-EGC-G1#8]
Implementación de las vistas necesarias. Estas comprenden:
- JSPs
- Ficheros de mensajes dinámicos (messages.properties)
- Tiles (tiles.xml)

Además se deberá definir el estilo de estas.

**Comment by YamiJosema** [comment]
Cierre para nuevo comienzo del proyecto haciendo uso de Python 2.7 con Django 1.5
